type t =
  | Ident of string (* x *)
  | App of t * t (* a b *)
  | Lam of binder_group list * t (* fun x y : T => e *)
  | Pi of typed_binder_group * t (* (x y : A) → B *)
  | Arrow of t * t (* A → B *)
  | Let of string * t option * t * t (* let x : A := a; b *)
  | U (* Type *)
  | Sigma of typed_binder_group * t (* (x y : A) × B *)
  | Prod of t * t (* A × B *)
  | Pair of t * t (* (a, b) *)
  | Eq of t * t (* a = b, desugars to Eq _ a b *)
  | NatLit of int (* 0 *)
  | Add of t * t (* a + b *)
  | Sub of t * t (* a - b *)
  | Ann of t * t (* generated by defs *)
  | Sorry (* sorry *)

and binder_group =
  | Untyped of string
  | Typed of typed_binder_group

and typed_binder_group = string option list * t

type field = {
  name : string;
  binders : typed_binder_group list;
  ty : t;
}

type constructor = {
  name : string;
  params : typed_binder_group list;
  ty : t option;
}

type inductive_info = {
  name : string;
  params : typed_binder_group list;
  ty : t option;
  ctors : constructor list;
}

type structure_info = {
  name : string;
  params : typed_binder_group list;
  ty : t option;
  fields : field list;
}

type item =
  | Import of { module_name : string } (* import Foo.Bar *)
  | Def of {
      name : string;
      body : t;
    }
  | Example of { body : t }
  | Inductive of inductive_info
  | Structure of structure_info

type program = item list
