id = "qdt"
name = "QDT"
description = "QDT language support"
version = "0.0.1"
schema_version = 1
authors = ["IntGrah"]
repository = "https://github.com/IntGrah/qdt"

[language_servers.qdt]
name = "QDT"
languages = ["QDT"]

[grammars.qdt]
repository = "https://github.com/IntGrah/qdt"
commit = "307b7bdc336c26619171ca20b916717d5806f9f0"
path = "tree-sitter-qdt"
