(* ========== Raw Syntax ========== *)

type raw =
  | RIdent of string (* x *)
  | RApp of raw * raw (* a b *)
  | RLam of binder list * raw (* fun x y : T => e *)
  | RPi of binder_group * raw (* (x y : A) → B *)
  | RArrow of raw * raw (* A → B *)
  | RLet of string * raw option * raw * raw (* let x : A := a; b *)
  | RU (* Type *)
  | RUnit (* Unit *)
  | RUnitTm (* () *)
  | REmpty (* Empty *)
  | RAbsurd of raw (* absurd a *)
  | REq of raw * raw (* a = b *)
  | RRefl of raw (* refl a *)
  | RSigma of binder_group * raw (* (x y : A) × B *)
  | RProd of raw * raw (* A × B *)
  | RPair of raw * raw (* (a, b) *)
  | RProj1 of raw (* fst e *)
  | RProj2 of raw (* fst e *)
  | RInt (* Int *)
  | RIntLit of int (* 0 *)
  | RAdd of raw * raw (* a + b *)
  | RSub of raw * raw (* a - b *)
  | RAnn of raw * raw (* generated by defs *)
  | RSorry (* sorry *)

and binder = string option * raw option
and binder_group = string option list * raw

type raw_def = RDef of string * raw
type raw_program = raw_def list

(* ========== Core Syntax ========== *)

type lvl = int

type ty =
  | TyU
  | TyPi of string option * ty * ty
  | TySigma of string option * ty * ty
  | TyUnit
  | TyEmpty
  | TyInt
  | TyEq of tm * tm * ty
  | TyEl of tm

and tm =
  | TmVar of lvl (* de Bruijn index *)
  | TmLam of string option * ty * ty * tm
  | TmApp of tm * tm
  | TmPiHat of string option * tm * tm
  | TmSigmaHat of string option * tm * tm
  | TmMkSigma of ty * ty * tm * tm
  | TmProj1 of tm
  | TmProj2 of tm
  | TmUnit
  | TmAbsurd of ty * tm
  | TmIntLit of int
  | TmUnitHat
  | TmEmptyHat
  | TmIntHat
  | TmEqHat of tm * tm * ty
  | TmRefl of ty * tm
  | TmAdd of tm * tm
  | TmSub of tm * tm
  | TmSorry of ty
  | TmLet of string * ty * tm * tm

(* Weak head normal form *)
type vl_ty =
  | VTyU
  | VTyPi of string option * vl_ty * clos_ty
  | VTySigma of string option * vl_ty * clos_ty
  | VTyUnit
  | VTyEmpty
  | VTyInt
  | VTyEq of vl_tm * vl_tm * vl_ty
  | VTyEl of neutral

(* Weak head normal form *)
and vl_tm =
  | VTmNeutral of neutral
  | VTmLam of string option * vl_ty * clos_tm
  | VTmPiHat of string option * vl_tm * clos_tm
  | VTmSigmaHat of string option * vl_tm * clos_tm
  | VTmMkSigma of string option * vl_ty * clos_ty * vl_tm * vl_tm
  | VTmUnit
  | VTmAbsurd of vl_ty * vl_tm
  | VTmIntLit of int
  | VTmUnitHat
  | VTmEmptyHat
  | VTmIntHat
  | VTmEqHat of vl_tm * vl_tm * vl_ty
  | VTmRefl of vl_ty * vl_tm
  | VTmAdd of vl_tm * vl_tm
  | VTmSub of vl_tm * vl_tm
  | VTmSorry of vl_ty

and spine = fname list

and fname =
  | FApp of vl_tm
  | FProj1
  | FProj2

and head =
  | HVar of lvl (* de Bruijn level *)
  | HConst of string

and neutral = head * spine
and clos_ty = ClosTy of env * ty
and clos_tm = ClosTm of env * tm
and env = vl_tm list
